### ISSUE TITLE
[Bug]: Upload fails due to trying to call invalid method on `list`

### ISSUE THREAD

**Issue by milanvarady** [TheAcharya/csv2notion-neo#16]
### CSV2Notion Neo Version?

1.1.1

### What OS are you using?

MacOS

### OS Version or Linux distribution

macOS 14.2.1

### Bug Description

Hi, I'm the developer of MarkerData which is the GUI app for MarkersExtractor. I'm now trying to adapt the new JSON export, but I keep getting this error: `AttributeError: 'list' object has no attribute 'split'`

I tried to dig into the code a bit, but couldn't figure out what is causing this. Maybe you can take a look.

Here are the CLI arguments I used:

`./csv2notion_neo --token {token} --url "https://www.notion.so/{url}" --image-column "Image Filename" --image-column-keep --mandatory-column "Marker ID" --payload-key-column "Marker ID" --icon-column "Icon Image" --max-threads 5 --merge --log {log_folder} ".../Marker Data Demo_V1.json"`

And here is the command line output:

```
INFO: CSV2Notion Neo version 1.1.1
INFO: Validating json & Notion DB schema
INFO: Uploading Marker Data Demo_V1.json...
Traceback (most recent call last):
  File "csv2notion_neo/__main__.py", line 5, in <module>
  File "csv2notion_neo/cli.py", line 96, in main
  File "csv2notion_neo/cli.py", line 59, in cli
  File "csv2notion_neo/cli_steps.py", line 79, in upload_rows
  File "tqdm/std.py", line 1178, in __iter__
  File "csv2notion_neo/utils_threading.py", line 38, in process_iter
  File "csv2notion_neo/utils_threading.py", line 38, in <genexpr>
  File "concurrent/futures/_base.py", line 437, in result
  File "concurrent/futures/_base.py", line 389, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "csv2notion_neo/utils_threading.py", line 26, in worker
  File "csv2notion_neo/notion_uploader.py", line 25, in upload_row
  File "csv2notion_neo/notion_uploader.py", line 41, in _get_db_row
  File "csv2notion_neo/notion_db.py", line 104, in add_row
  File "csv2notion_neo/notion_db_collection.py", line 38, in add_row_block
  File "csv2notion_neo/notion_db_collection.py", line 71, in _add_row_block
  File "notion/collection.py", line 471, in __setattr__
  File "csv2notion_neo/notion_row.py", line 149, in set_property
  File "csv2notion_neo/notion_row.py", line 193, in _convert_python_to_notion
  File "notion/collection.py", line 651, in _convert_python_to_notion
AttributeError: 'list' object has no attribute 'split'
[58681] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by IAmVigneswaran** [comment]
@milanvarady

I have just tested at my end. I did not get any error. I was able to upload the .json file to Notion.

Could you test again?

`
$TOOL_PATH --token $NOTION_TOKEN --url $NOTION_URL --image-column "Image Filename" --image-column-keep --mandatory-column "Marker ID" --icon-column "Icon Image" --payload-key-column "Marker ID" --max-threads 5 --merge --log $UPLOAD_LOG --verbose "$UPLOAD_PAYLOAD"`

**Comment by milanvarady** [comment]
>Could you test again?
>`$TOOL_PATH --token $NOTION_TOKEN --url $NOTION_URL --image-column "Image Filename" --image-column-keep --mandatory-column "Marker ID" --icon-column "Icon Image" --payload-key-column "Marker ID" --max-threads 5 --merge --log $UPLOAD_LOG --verbose "$UPLOAD_PAYLOAD"`

@IAmVigneswaran I've tried with these exact arguments and still got the same error.

**Comment by arjunprakash027** [comment]
@milanvarady If you are using the python code directly (not using the binary), did you pull the changes?
also there is a new branch callled custom-fix-1, also try using that code once and let me know.

I could not reproduce the error at my end.

**Comment by milanvarady** [comment]
@arjunprakash027 I used the precompiled binary [v1.1.1](https://github.com/TheAcharya/csv2notion-neo/releases/tag/v1.1.1).

**Comment by arjunprakash027** [comment]
> @arjunprakash027 I used the precompiled binary [v1.1.1](https://github.com/TheAcharya/csv2notion-neo/releases/tag/v1.1.1).

@milanvarady was it precompiled recently? I made some changes 2 weeks ago that fixed the issue you are mentioning.

**Comment by milanvarady** [comment]
@arjunprakash027 It is this [exact binary](https://github.com/TheAcharya/csv2notion-neo/releases/download/v1.1.1/bin_csv2notion_neo_1.1.1_macos_x64.zip) which was published 21st December 2023. So in theory it should work then. Weird.

**Comment by arjunprakash027** [comment]
@milanvarady It should have worked...weird.
Can you create a new build from the main branch and test once?

**Comment by milanvarady** [comment]
I run it both on the main and the custom-fix-1 branch. No luck, unfortunately. I haven't used poetry before, I did like `poetry run csv2notion_neo --token {token} --url {url}...`. Not sure if this is how it should be. I got a different traceback this time, maybe it helps to narrow the issue down.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/cli.py", line 95, in main
    cli(*sys.argv[1:])
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/cli.py", line 58, in cli
    upload_rows(
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/cli_steps.py", line 79, in upload_rows
    list(tdqm_iter)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/csv2notion-neo-ar2JGjpa-py3.12/lib/python3.12/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/utils_threading.py", line 38, in process_iter
    yield from (f.result() for f in as_completed(futures))
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/utils_threading.py", line 38, in <genexpr>
    yield from (f.result() for f in as_completed(futures))
                ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/utils_threading.py", line 26, in worker
    notion_uploader.upload_row(*args, **kwargs)
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion_uploader.py", line 25, in upload_row
    db_row = self._get_db_row(row, is_merge)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion_uploader.py", line 43, in _get_db_row
    cur_row = self.db.add_row(properties=row.properties, columns=row.columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion_db.py", line 106, in add_row
    new_row = self.collection.add_row_block(properties=properties, columns=columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion_db_collection.py", line 39, in add_row_block
    new_row = self._add_row_block(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion_db_collection.py", line 72, in _add_row_block
    setattr(row.columns, key, val)
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion/collection.py", line 474, in __setattr__
    self._parent.set_property(slugify(attname), value)
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion_row.py", line 149, in set_property
    path, new_value = self._convert_python_to_notion(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion_row.py", line 193, in _convert_python_to_notion
    return super()._convert_python_to_notion(raw_value, prop, identifier)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/GitHub/csv2notion-neo/csv2notion_neo/notion/collection.py", line 654, in _convert_python_to_notion
    val = val.split(",")[0]
          ^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
```

**Comment by IAmVigneswaran** [comment]
@milanvarady Thanks for reporting.
