### ISSUE TITLE
[Bug]: Regression in convert_csv_to_notion_rows

### ISSUE THREAD

**Issue by latenitefilms** [TheAcharya/csv2notion-neo#21]
### CSV2Notion Neo Version?

1.2.0

### What OS are you using?

MacOS

### OS Version or Linux distribution

macOS Sonoma 14.1.2

### Bug Description

It seems like there's a regression in `convert_csv_to_notion_rows` (compared to `csv2notion` v0.3.8):

```
CommandPost v1.4.23 (Build: 8011)

Build Date:                     Jan 18 2024, 16:29:50
macOS Version:                  14.1.2
CommandPost Locale:             en_AU
Current Keyboard Layout:        Australian
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.7.1
Final Cut Pro Language:         en
Developer Mode:                 true

2024-01-19 09:04:20: -- Loading /Users/chrishocking/Documents/GitHub/CommandPost/src/extensions/cp/init.lua
2024-01-19 09:04:21: 
2024-01-19 09:04:21: 09:04:21         cp:     Loading Plugins...
2024-01-19 09:04:36: 09:04:36 ** Warning:   plugins: Slow Plugin: finalcutpro.setup.scan (13.094498157501)
2024-01-19 09:04:38: 09:04:38 ** Warning:   plugins: Slow Plugin: core.loupedeckctandlive.manager (1.3391659259796)
2024-01-19 09:04:38: 09:04:38 ** Warning:   plugins: Slow Plugin: core.menu.menuaction (1.7502868175507)
2024-01-19 09:04:39: 09:04:39         cp:     Plugins Loaded.
2024-01-19 09:04:39:                          Startup Time: 17.752238 seconds
2024-01-19 09:04:39:                          Garbage Collection Mode: generational
2024-01-19 09:04:39: -- Done.
2024-01-19 09:05:11: 09:05:11     notion:     Notion Upload Status: CSV2Notion Neo version 1.2.0...
2024-01-19 09:05:11:                          Notion Upload Status: Validating csv & csv2notion_neo.notion DB schema...
2024-01-19 09:05:11:                          Notion Upload Status: Creating new database...
2024-01-19 09:05:14: 09:05:14                 Notion Upload Status: New database URL: https://www.notion.so/a23bf411cab34533bb8d87c1ef6a1d41...
2024-01-19 09:05:14:                          Notion Upload Status: Traceback (most recent call last):  File "csv2notion_neo/__main__.py", line 5, in <module>  File "csv2notion_neo/cli.py", line 95, in main  File "csv2notion_neo/cli.py", line 52, in cli  File "csv2notion_neo/cli_steps.py", line 53, in convert_csv_to_notion_rows  File "csv2notion_neo/notion_preparator.py", line 43, in prepare  File "csv2notion_neo/notion_preparator.py", line 47, in _validate_image_columnTypeError: 'NoneType' object is not iterable[55642] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by IAmVigneswaran** [comment]
@latenitefilms Thanks for reporting. The issue has been fixed with build 1.2.1.
