### ISSUE TITLE
Error - `file extension not supported` & `Mandatory column(s) {'Reel'} not found in csv file`.

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/csv2notion-neo#43]
@arjunprakash027 

@samplue Reports the following issue with 1.3.2 when he is trying to upload a data set to his Notion Database.

```
INFO: CSV2Notion Neo version 1.3.2
INFO: Validating csv & csv2notion_neo.notion DB schema
WARNING: Inconsistent number of columns detected. Excess columns will be truncated.
ERROR: Error at division
Traceback (most recent call last):
  File "csv2notion_neo/cli.py", line 53, in cli
  File "csv2notion_neo/cli_steps.py", line 53, in convert_csv_to_notion_rows
  File "csv2notion_neo/notion_preparator.py", line 43, in prepare
  File "csv2notion_neo/notion_preparator.py", line 81, in _validate_mandatory_columns
csv2notion_neo.utils_exceptions.NotionError: Mandatory column(s) {'Reel'} not found in csv file.
```

From his .sh Script: 

`"$TOOL_PATH" --workspace "$NOTION_WORKSPACE" --token $NOTION_TOKEN --url $NOTION_URL --mandatory-column "Reel" --max-threads 10 --merge --log "$UPLOAD_LOG" --verbose "$UPLOAD_PAYLOAD"`

Interestedly I am getting a different error when attempting reproduce his error.

```
2024-11-09 08:57:58,956 [INFO    ] CSV2Notion Neo version 1.3.2
2024-11-09 08:57:58,957 [INFO    ] Validating  & csv2notion_neo.notion DB schema
2024-11-09 08:57:58,957 [ERROR   ] Error at division
Traceback (most recent call last):
  File "csv2notion_neo/cli.py", line 35, in cli
  File "csv2notion_neo/local_data.py", line 113, in __init__
  File "csv2notion_neo/local_data.py", line 34, in data_read
csv2notion_neo.utils_exceptions.CriticalError:  file extension not supported!
```

**Comment by arjunprakash027** [comment]
@samplue -  The problem was due to your csv delimited by ; instead of ,

Fixed the problem by letting you mention the delimiter in the command itself.

Please download the latest version and try out this command 

`$TOOL_PATH --token $NOTION_TOKEN --url $NOTION_URL --mandatory-column "Reel" --delimiter ";" --max-threads 5 --merge --verbose --workspace "$NOTION_WORKSPACE" "$UPLOAD_CSV"
`
