### ISSUE TITLE
Error merging data into existing database

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/csv2notion-neo#8]
A user reports that merging `*.csv` data with his existing database throws this error.

```
Traceback (most recent call last):
  File "csv2notion_neo/main.py", line 4, in <module>
  File "csv2notion_neo/cli.py", line 82, in main
  File "csv2notion_neo/cli.py", line 45, in cli
  File "csv2notion_neo/cli_steps.py", line 77, in upload_rows
  File "tqdm/std.py", line 1178, in iter
  File "csv2notion_neo/utils_threading.py", line 38, in process_iter
  File "csv2notion_neo/utils_threading.py", line 38, in <genexpr>
  File "concurrent/futures/_base.py", line 437, in result
  File "concurrent/futures/_base.py", line 389, in get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "csv2notion_neo/utils_threading.py", line 26, in worker
  File "csv2notion_neo/notion_uploader.py", line 24, in upload_row
  File "csv2notion_neo/notion_uploader.py", line 40, in _get_db_row
  File "csv2notion_neo/notion_db.py", line 104, in add_row
  File "csv2notion_neo/notion_db_collection.py", line 37, in add_row_block
  File "notion/collection.py", line 231, in add_row_block
  File "notion/client.py", line 469, in exit
  File "notion/client.py", line 323, in submit_transaction
  File "ratelimit/decorators.py", line 113, in wrapper
  File "ratelimit/decorators.py", line 80, in wrapper
  File "notion/client.py", line 275, in post
  File "notion/client.py", line 298, in _post
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: https://www.notion.so/api/v3/submitTransaction
[17913] Failed to execute script 'main__' due to unhandled exception!
```

**Comment by IAmVigneswaran** [comment]
@vzhd1701 Could you provide any insights on this issue. Thank you.

**Comment by latenitefilms** [comment]
@IAmVigneswaran - `Payload Too Large` makes it sounds as if you were basically just sending too much data to the Notion API.

**Comment by IAmVigneswaran** [comment]
> `Payload Too Large` makes it sounds as if you were basically just sending too much data to the Notion API.

The sample Notion Database was empty and `*.csv` payload only had 100+ records. 

Not sure if it is due to rate limit.

**Comment by IAmVigneswaran** [comment]
@vzhd1701 Thanks for fixing the issue! Will get feedback from the user.
